import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import Grid from "@mui/material/Grid";
import styles from "../styles/Home.module.css";
import TextField from "@mui/material/TextField";
import MenuItem from "@mui/material/MenuItem";
import { Game, getGames } from "../firebase/firestore";
import { gameActions, gameSelectors } from "../states/gameState";

const Home: NextPage = () => {
  const [gameId, setGameId] = React.useState("");
  const [games, setGames] = React.useState([] as Game[]);

  const handleChange = (game: React.ChangeEvent<HTMLInputElement>) => {
    setGameId(game.target.value);
    const selectedGame = games.find((v) => {
      return v.id === gameId;
    }) ?? { id: "", name: "" };
    gameActions.useAddGameItem(selectedGame);
    const id = gameSelectors.useGames();
    console.log(id);
  };
  React.useEffect(() => {
    (async function () {
      try {
        const gameList = await getGames();
        setGames(gameList);
      } catch {
        // 未ログイン（未ログイン時のリダイレクト処理などをここに書いても良いかも）
        console.log("error");
      }
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid container justifyContent="center" alignItems="center" spacing={2}>
          <Grid item xs={12}>
            <h2>Welcome to SNC Portal!</h2>
          </Grid>
          <Grid item xs={10}>
            <TextField
              id="outlined-select-currency"
              select
              fullWidth
              label="Select"
              value={gameId}
              onChange={handleChange}
              helperText="試合名を選択してください"
            >
              {games.map((option) => (
                <MenuItem key={option.id} value={option.id}>
                  {option.name}
                </MenuItem>
              ))}
            </TextField>
          </Grid>
        </Grid>

        <p>Now game id is {gameId}</p>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
